### ISSUE TITLE
comments box got vanished

### ISSUE THREAD

**Issue by bharathganji** [wpsocio/wptelegram-comments#20]
hi team,

i don't know when happened but comments box got vanished..
![image](https://user-images.githubusercontent.com/59326887/226595464-13806520-e0a9-4a30-8d74-8b5442bbb02f.png)

here is my site, check once, every post same problem, i've custom post(plugin generated) and default WordPress posts.

**Comment by irshadahmad21** [comment]
The expected output should be something like this

![image](https://user-images.githubusercontent.com/94346512/226597381-a78aec0e-168c-47c9-b583-5efb9315fff5.png)

I see that the scrip `src` is missing in your case. Do you have any caching/optimization plugin active?

**Comment by bharathganji** [comment]
Yes, i use 10web.io plugin, but this was there from starting, i've tried with disabling it.
No change

Can u provide any alternative for me

**Comment by irshadahmad21** [comment]
It's some plugin conflict or caching issue. Try deactivating the plugins to find out which one causes the issue. It can also be your theme that strips out the JavaScript.
